server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - http://localhost:3000
              - http://localhost:5173
              - http://localhost:8443
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - '*'
            exposed-headers:
              - Location
            allow-credentials: true
            max-age: 3600

      discovery:
        locator:
          enabled: false

      routes:
        - id: product-service-read
          uri: lb://product-service
          predicates:
            - Path=${controllers.products.base-path}/**, ${controllers.categories.base-path}/**
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
              methods:
                - GET
              backoff:
                firstBackoff: 100ms
                maxBackoff: 500ms

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${controllers.products.base-path}/**, ${controllers.categories.base-path}/**

        - id: inventory-service-read
          uri: lb://inventory-service
          predicates:
            - Path=${controllers.inventory.base-path}/**
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
              methods:
                - GET
              backoff:
                firstBackoff: 100ms
                maxBackoff: 500ms

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=${controllers.inventory.base-path}/**

        - id: order-service-read
          uri: lb://order-service
          predicates:
            - Path=${controllers.order.base-path}/**
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
              methods:
                - GET
              backoff:
                firstBackoff: 100ms
                maxBackoff: 500ms

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=${controllers.order.base-path}/**