server:
  port: 8888

spring:
  main:
    banner-mode: off
    log-startup-info: false
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./infra/config-repo
            - file:./infra/config-repo/telemetry
            - file:./infra/config-repo/commerce